export const AIRGRAM_CLIENT = 'AIRGRAM_CLIENT';
export const AIRGRAM_MODULE_OPTIONS = 'AIRGRAM_MODULE_OPTIONS';

export const EVENT_LISTENER_TYPE = 'EVENT_LISTENER_TYPE';
export const EVENT_LISTENER_EVENT_NAME = 'EVENT_LISTENER_EVENT_NAME';
